title: Advocacia Visual - Visual Law
email: contato@advocaciavisual.com.br
description: >-
  Advocacia Visual mostra como os advogados podem fazer melhor uso do Visual Law para sua prática diária na advocacia.
  Eduque-se sobre técnicas de comunicação visual, design de documentos legais e apresentações impactantes.
baseurl: ""
url: "https://advocaciavisual.com.br"
timezone: America/Sao_Paulo
locale: pt_BR
future: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  authors:
    output: true
    permalink: /autores/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "admin"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - DESIGN-REFERENCE.md
  - Dockerfile
  - docker-compose.yml
  - start.sh
  - test.sh
  - fetch_migalhas.sh
  - fetch_articles.rb
  - extract_content.rb
  - .jekyll-cache
  - .sass-cache
  - .bundle
  - .github
  - .ruby-version
  - .node-version
  - spec
  - Rakefile
  - vercel.json
  - docs/
  - .env
